export const airports = [
  { key: "ALB", value: "ALB", label: "Albany, NY - ALB" },
  { key: "ABQ", value: "ABQ", label: "Albuquerque, NM - ABQ" },
  { key: "AMA", value: "AMA", label: "Amarillo, TX - AMA" },
  { key: "AUA", value: "AUA", label: "Aruba, Aruba - AUA" },
  { key: "ATL", value: "ATL", label: "Atlanta, GA - ATL" },
  { key: "AUS", value: "AUS", label: "Austin, TX - AUS" },
  { key: "BWI", value: "BWI", label: "Baltimore/Washington, MD - BWI" },
  { key: "BZE", value: "BZE", label: "Belize City, Belize - BZE" },
  { key: "BHM", value: "BHM", label: "Birmingham, AL - BHM" },
  { key: "BOI", value: "BOI", label: "Boise, ID - BOI" },
  { key: "BOS", value: "BOS", label: "Boston Logan, MA - BOS" },
  { key: "BUF", value: "BUF", label: "Buffalo/Niagara, NY - BUF" },
  { key: "BUR", value: "BUR", label: "Burbank, CA - BUR" },
  { key: "SJD", value: "SJD", label: "Cabo San Lucas/Los Cabos, MX - SJD" },
  { key: "CUN", value: "CUN", label: "Cancun, Mexico - CUN" },
  { key: "CHS", value: "CHS", label: "Charleston, SC - CHS" },
  { key: "CLT", value: "CLT", label: "Charlotte, NC - CLT" },
  { key: "MDW", value: "MDW", label: "Chicago (Midway), IL - MDW" },
  { key: "CVG", value: "CVG", label: "Cincinnati, OH - CVG" },
  { key: "CLE", value: "CLE", label: "Cleveland, OH - CLE" },
  { key: "CMH", value: "CMH", label: "Columbus, OH - CMH" },
  { key: "CRP", value: "CRP", label: "Corpus Christi, TX - CRP" },
  { key: "DAL", value: "DAL", label: "Dallas (Love Field), TX - DAL" },
  { key: "DEN", value: "DEN", label: "Denver, CO - DEN" },
  { key: "DSM", value: "DSM", label: "Des Moines, IA - DSM" },
  { key: "DTW", value: "DTW", label: "Detroit, MI - DTW" },
  { key: "ELP", value: "ELP", label: "El Paso, TX - ELP" },
  { key: "FNT", value: "FNT", label: "Flint, MI - FNT" },
  { key: "FLL", value: "FLL", label: "Ft. Lauderdale, FL - FLL" },
  { key: "RSW", value: "RSW", label: "Ft. Myers, FL - RSW" },
  { key: "GCM", value: "GCM", label: "Grand Cayman, Cayman Islands - GCM" },
  { key: "GRR", value: "GRR", label: "Grand Rapids, MI - GRR" },
  { key: "GSP", value: "GSP", label: "Greenville/Spartanburg, SC - GSP" },
  { key: "HRL", value: "HRL", label: "Harlingen, TX - HRL" },
  { key: "BDL", value: "BDL", label: "Hartford, CT - BDL" },
  { key: "HAV", value: "HAV", label: "Havana, Cuba - HAV" },
  { key: "HOU", value: "HOU", label: "Houston (Hobby), TX - HOU" },
  { key: "IND", value: "IND", label: "Indianapolis, IN - IND" },
  { key: "JAX", value: "JAX", label: "Jacksonville, FL - JAX" },
  { key: "MCI", value: "MCI", label: "Kansas City, MO - MCI" },
  { key: "LAS", value: "LAS", label: "Las Vegas, NV - LAS" },
  { key: "LIR", value: "LIR", label: "Liberia, Costa Rica - LIR" },
  { key: "LIT", value: "LIT", label: "Little Rock, AR - LIT" },
  { key: "LGB", value: "LGB", label: "Long Beach, CA - LGB" },
  { key: "ISP", value: "ISP", label: "Long Island/Islip, NY - ISP" },
  { key: "LAX", value: "LAX", label: "Los Angeles, CA - LAX" },
  { key: "SDF", value: "SDF", label: "Louisville, KY - SDF" },
  { key: "LBB", value: "LBB", label: "Lubbock, TX - LBB" },
  { key: "MHT", value: "MHT", label: "Manchester, NH - MHT" },
  { key: "MEM", value: "MEM", label: "Memphis, TN - MEM" },
  { key: "MEX", value: "MEX", label: "Mexico City, Mexico - MEX" },
  { key: "MAF", value: "MAF", label: "Midland/Odessa, TX - MAF" },
  { key: "MKE", value: "MKE", label: "Milwaukee, WI - MKE" },
  {
    key: "MSP",
    value: "MSP",
    label: "Minneapolis/St. Paul (Terminal 2), MN - MSP"
  },
  { key: "MBJ", value: "MBJ", label: "Montego Bay, Jamaica - MBJ" },
  { key: "BNA", value: "BNA", label: "Nashville, TN - BNA" },
  { key: "NAS", value: "NAS", label: "Nassau, Bahamas - NAS" },
  { key: "MSY", value: "MSY", label: "New Orleans, LA - MSY" },
  { key: "LGA", value: "LGA", label: "New York (LaGuardia), NY - LGA" },
  { key: "EWR", value: "EWR", label: "New York/Newark, NJ - EWR" },
  { key: "ORF", value: "ORF", label: "Norfolk, VA - ORF" },
  { key: "OAK", value: "OAK", label: "Oakland, CA - OAK" },
  { key: "OKC", value: "OKC", label: "Oklahoma City, OK - OKC" },
  { key: "OMA", value: "OMA", label: "Omaha, NE - OMA" },
  { key: "ONT", value: "ONT", label: "Ontario/LA, CA - ONT" },
  { key: "SNA", value: "SNA", label: "Orange County/Santa Ana, CA - SNA" },
  { key: "MCO", value: "MCO", label: "Orlando, FL - MCO" },
  { key: "ECP", value: "ECP", label: "Panama City Beach, FL - ECP" },
  { key: "PNS", value: "PNS", label: "Pensacola, FL - PNS" },
  { key: "PHL", value: "PHL", label: "Philadelphia, PA - PHL" },
  { key: "PHX", value: "PHX", label: "Phoenix, AZ - PHX" },
  { key: "PIT", value: "PIT", label: "Pittsburgh, PA - PIT" },
  { key: "PDX", value: "PDX", label: "Portland, OR - PDX" },
  { key: "PWM", value: "PWM", label: "Portland, ME - PWM" },
  { key: "PVD", value: "PVD", label: "Providence, RI - PVD" },
  { key: "PLS", value: "PLS", label: "Providenciales, Turks and Caicos - PLS" },
  { key: "PVR", value: "PVR", label: "Puerto Vallarta, MX - PVR" },
  { key: "PUJ", value: "PUJ", label: "Punta Cana, DO - PUJ" },
  { key: "RDU", value: "RDU", label: "Raleigh/Durham, NC - RDU" },
  { key: "RNO", value: "RNO", label: "Reno/Tahoe, NV - RNO" },
  { key: "RIC", value: "RIC", label: "Richmond, VA - RIC" },
  { key: "ROC", value: "ROC", label: "Rochester, NY - ROC" },
  { key: "SMF", value: "SMF", label: "Sacramento, CA - SMF" },
  { key: "SLC", value: "SLC", label: "Salt Lake City, UT - SLC" },
  { key: "SAT", value: "SAT", label: "San Antonio, TX - SAT" },
  { key: "SAN", value: "SAN", label: "San Diego, CA - SAN" },
  { key: "SFO", value: "SFO", label: "San Francisco, CA - SFO" },
  { key: "SJC", value: "SJC", label: "San Jose, CA - SJC" },
  { key: "SJO", value: "SJO", label: "San Jose, Costa Rica - SJO" },
  { key: "SJU", value: "SJU", label: "San Juan, PR - SJU" },
  { key: "SEA", value: "SEA", label: "Seattle/Tacoma, WA - SEA" },
  { key: "GEG", value: "GEG", label: "Spokane, WA - GEG" },
  { key: "STL", value: "STL", label: "St. Louis, MO - STL" },
  { key: "TPA", value: "TPA", label: "Tampa, FL - TPA" },
  { key: "TUS", value: "TUS", label: "Tucson, AZ - TUS" },
  { key: "TUL", value: "TUL", label: "Tulsa, OK - TUL" },
  { key: "IAD", value: "IAD", label: "Washington (Dulles), DC - IAD" },
  { key: "DCA", value: "DCA", label: "Washington (Reagan National), DC - DCA" },
  { key: "PBI", value: "PBI", label: "West Palm Beach, FL - PBI" },
  { key: "ICT", value: "ICT", label: "Wichita, KS - ICT" }
];
